### ISSUE TITLE
Restorer-restore() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by kjaksic** [clarinsi/reldi-lib#4]
Dear admins, 

I installed reldi library in python 2.7.18.  I was able to replicate your code for all examples, but restorer. 

When I run restorer, value error is raised: ""restore() takes exactly 2 arguments (1 given)" 

Code is: 
import json
from reldi.restorer import DiacriticRestorer
dr=DiacriticRestorer('hr')
dr.authorize('myname','mypassword')
json.loads(dr.restore('Cudil bi se da ovo dela.'))  

Thank you for your suggestions.

**Comment by amilinko** [comment]
Hi,

Can you please provide more details about this error? Do you have the stacktrace of exception?
The restore method takes 1 required and 1 optional argument. You have passed the string and this must work.
Have you successfully sent HTTP request? Did your authorization go well?

**Comment by kjaksic** [comment]
Hi, 

code is working until last line: json.loads(dr.restore(u'Cudil bi se da ovo dela.')). Authorization went well and was also able to replicate another examples (parser, tagger, lexicon, NERTagger). 

Full error is: 
 Traceback (most recent call last):
  File "C:\Users\myname\primjeri.py", line 5, in <module>
    json.loads(dr.restore(u'Cudil bi se da ovo dela.'))
  File "C:\Python27\lib\site-packages\reldi\restorer.py", line 28, in restore
    return self.queryApi("{0}/restore".format(self.language), params)
  File "C:\Python27\lib\site-packages\reldi\client.py", line 38, in queryApi
    raise ValueError(response.read())
ValueError: "restore() takes exactly 2 arguments (1 given)"

Code that is given above is the only code in the script. I was checking examples before putting code into my project.

**Comment by nljubesi** [comment]
Far too late I have resolved the issue by digging rather deep in the code at https://github.com/clarinsi/reldi-api/ where the issue resided due to @amilinko not updating the full code. I hope, @kjaksic, you can still profit from the services at this late hour. Better late than never. cc @TomazErjavec

**Comment by kjaksic** [comment]
Thank you for the feedback. It is great you were able to solve the issue.
Reldi is great package and I am looking forward to using it in the future.

čet, 17. pro 2020. 17:32 Nikola Ljubešić <notifications@github.com> je
napisao:
